apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-microservice
  template:
    metadata:
      labels:
        app: flask-microservice
    spec:
      containers:
      - name: flask-app
        image: anummdocker/flask-devops-app:b11c967ce744eba15d7113b854cea3e62774d08a
        ports:
        - containerPort: 5000

