apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-microservice
  template:
    metadata:
      labels:
        app: flask-microservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"     # The port your Flask container runs on
        prometheus.io/path: "/metrics"  # The endpoint where metrics are exposed  
    spec:
      containers:
      - name: flask-app
        image: anummdocker/flask-devops-app:2635d2e888f8b3ca4971d7aba9d7b9c84d62f5c0
        ports:
        - containerPort: 5000

