apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-microservice
  template:
    metadata:
      labels:
        app: flask-microservice
    spec:
      containers:
      - name: flask-app
        image: anummdocker/flask-devops-app:669959d509edcbcb9c1cb2cbfbdf52276843e61c
        ports:
        - containerPort: 5000

